version: '3.7'
services:

    sim:
        build: ./sim
        image: sim
        cap_add:
            - NET_ADMIN
 
    server:
        build: ./h2o-qns
        image: quicly
        name: server
        depends_on:
            - sim
        cap_add:
            - NET_ADMIN
        hostname: server
        ip: 192.168.100.100       
