version: 2
jobs:
  build:
    docker:
      - image: "circleci/golang:1.12"
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: |
            cd sim
            docker build . -t quic-network-simulator
