version: 2.1
executors:
  docker-publisher:
    environment:
      ENDPOINT_IMAGE_NAME: martenseemann/quic-network-simulator-endpoint
      SIMULATOR_IMAGE_NAME: martenseemann/quic-network-simulator
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build-endpoint:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image for the endpoint
          command: docker build endpoint -t $ENDPOINT_IMAGE_NAME:latest
      - run:
          name: Archive Docker image
          command: docker save -o image-endpoint.tar $ENDPOINT_IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image-endpoint.tar
  build-simulator:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image for the simulator
          command: docker build sim -t $SIMULATOR_IMAGE_NAME:latest
      - run:
          name: Archive Docker image
          command: docker save -o image-simulator.tar $SIMULATOR_IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image-simulator.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Load archived Docker image (for the endpoint)
          command: docker load -i /tmp/workspace/image-endpoint.tar
      - run:
          name: Publish quic-network-simulator-endpoint
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $ENDPOINT_IMAGE_NAME:latest
      - run:
          name: Load archived Docker image (for the simulator)
          command: docker load -i /tmp/workspace/image-simulator.tar
      - run:
          name: Publish quic-network-simulator
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $SIMULATOR_IMAGE_NAME:latest

workflows:
  version: 2
  build-master:
    jobs:
      - build-endpoint
      - build-simulator
      - publish-latest:
          requires:
            - build-endpoint
            - build-simulator
          filters:
            branches:
              only: master
