version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: martenseemann/quic-network-simulator-endpoint
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build-endpoint:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image for the endpoint
          command: |
            cd endpoint
            docker build . -t $IMAGE_NAME:latest
      - run:
          name: Archive Docker image
          command: |
            cd endpoint
            docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./endpoint/image.tar
  publish-endpoint-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/endpoint/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

workflows:
  version: 2
  build-master:
    jobs:
      - build-endpoint
      - publish-endpoint-latest:
          requires:
            - build-endpoint
          filters:
            branches:
              only: master
